# Generated by Django 5.1.5 on 2025-04-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("Developer", "Developer"),
                ],
                default="user",
                max_length=100,
            ),
        ),
    ]
